### ISSUE TITLE
Keep getting "Referer checking failed does not match any trusted origins."

### ISSUE THREAD

**Issue by hthuong09** [galexrt/docker-healthchecks#15]
I keep getting this error when trying to login with an email. I don't know if something went wrong in my configurations.

#### docker-compose service
```yaml
  healthchecks:
    container_name: healthchecks
    image: galexrt/healthchecks:latest
    restart: always
    ports:
      - 10009:8000
    environment:
      - HC_HOST=192.168.1.20
      - HC_SECRET_KEY=hthuong09
      - HC_SITE_ROOT=https://healthchecks.thuongnguyen.me
      - HC_DEBUG=True
      - HC_ALLOWED_HOSTS=["healthcheck.[censored]","localhost"]
      - HC_CORS_ORIGIN_ALLOW_ALL=True
      - HC_CSRF_TRUSTED_ORIGINS=["healthcheck.[censored]"]

```
Not sure if `HC_CORS_ORIGIN_ALLOW_ALL` and `HC_CSRF_TRUSTED_ORIGINS` are configurable.

#### nginx-reversed proxy
I'm using [linuxserver's letsencrypt container](https://hub.docker.com/r/linuxserver/letsencrypt/) with the following config:
```
map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

server {
    include /config/nginx/ssl.conf;

    server_name  healthchecks.thuongnguyen.me;
    root        /config/www;
    index  index.html index.htm index.php;

    client_max_body_size 0;

    location / {
        proxy_pass http://localhost:10009;
    }
}
```

I'm able to access other function just fine. Except login function. Please take a look if there are something wrong or missing in my configs. Thanks.
