### ISSUE TITLE
Kubernetes Example

### ISSUE THREAD

**Issue by michidk** [galexrt/docker-healthchecks#16]
Hello,

thanks for this great image!
In case anyone needs this, here is a deployment, ingress, service example for Kubernetes using this image:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: healthchecks
spec:
  tls:
    - hosts:
        - health.yourdomain.com
  rules:
    - host: health.yourdomain.com
      http:
        paths:
          - path: /
            backend:
              serviceName: healthchecks
              servicePort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: healthchecks
  labels:
    app: healthchecks
spec:
  selector:
    app: healthchecks
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthchecks
  labels:
    app: healthchecks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthchecks
  template:
    metadata:
      labels:
        app: healthchecks
    spec:
      containers:
        - name: healthchecks
          image: galexrt/healthchecks
          env:
            - name: HC_HOST
              value: health.yourdomain.com
            - name: HC_SECRET_KEY
              value: f74567gvyfgcs43v45
            - name: HC_PING_EMAIL_DOMAIN
              value: health.yourdomain.com
            - name: HC_SITE_ROOT
              value: health.yourdomain.com
            - name: HC_EMAIL_HOST
              value: smtp.yourdomain.com
            - name: HC_EMAIL_PORT
              value: "25"
            - name: HC_EMAIL_USE_TLS
              value: "true"
            - name: HC_EMAIL_HOST_USER
              value: "noreply@yourdomain.com"
            - name: HC_EMAIL_HOST_PASSWORD
              value: asd321423wwdc
            - name: HC_ALLOWED_HOSTS
              value: '["*"]'
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: data
              mountPath: /healthchecks
      volumes:
        - name: data
          hostPath:
            path: /data/healthchecks
```
