### ISSUE TITLE
v1.13.0-0 does not contain the change from changelog

### ISSUE THREAD

**Issue by BobCashStory** [galexrt/docker-healthchecks#28]
Show sub-second durations with higher precision, 2 digits after decimal point (#321)
<img width="768" alt="Screenshot 2020-03-19 at 17 05 41" src="https://user-images.githubusercontent.com/47117399/77087850-e35a1800-6a03-11ea-8833-5a480a75c560.png">

Replace the gear icon with three horizontal dots icon (#322)
Add a Pause button in the checks list (#312)
<img width="1350" alt="Screenshot 2020-03-19 at 17 04 30" src="https://user-images.githubusercontent.com/47117399/77087709-b7d72d80-6a03-11ea-8651-146503019712.png">

<img width="90" alt="Screenshot 2020-03-19 at 17 04 51" src="https://user-images.githubusercontent.com/47117399/77087933-01c01380-6a04-11ea-8f89-e5e6b0768cb3.png">

Do you have any clue on why it's not as the changelog say ?
My docker compose
```
  healthchecks:
    container_name: healthchecks
    labels:
      - "com.ouroboros.enable=true" 
    networks:
      - galaxy_cs-tier    
    image: galexrt/healthchecks:v1.13.0-0
    restart: always
```
